# The URL the site will be built for
base_url = "https://blog.monotonous.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Monotonous"

theme = "linkita"

taxonomies = [
	{ name = "tags", feed = true }
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
styles = "monotonous.css"
header_buttons = ["site_title", "search_button", "translations_select"]